Repository CDDSCLab/training-plan, pull requests merged in 2020-07, with the labels that each got.

#1 Add Week1 Database Introduction Experiment
  README.md
  Week1-Database-Introduction/Example/李明实验报告.md
  Week1-Database-Introduction/JanusgraphExperiment.md
  Week1-Database-Introduction/README.md
Labels: need review, status/RP1

#4 add PR and Issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-question.md
  .github/pull_request_template.md
  .gitignore
Labels: need review, status/RP1

#3 init mysql
  Week1-Database-Introduction/MySQLExperiment.md
Labels: need review

#5 add images dir
  images/cddscl_icon.png
Labels: need review, status/RP1

#7 update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/general-question.md
Labels: need review, status/RP1

#8 add commit your work guide
  README.md
Labels: need review, status/RP2

#2 add Week1 Mongodb Experiment
  Week1-Database-Introduction/MongoDBExperiment.md
Labels: need review

#10 fix README Week2-3 Description
  README.md
Labels: need review, status/RP1

#11 Add MongoDBExperiment CourseM001
  Week1-Database-Introduction/MongoDBExperiment.md
Labels: need review

#13 朱道冰Week1
  Week1-Database-Introduction/DaoBingZhu-Week1/ExperimentReport.md
  Week1-Database-Introduction/DaoBingZhu-Week1/Mysql_SQL
  Week1-Database-Introduction/DaoBingZhu-Week1/images/godsGraph.jpg
  Week1-Database-Introduction/DaoBingZhu-Week1/images/gremlin-running.png
Labels: need review, status/RP1, weekly work

#22 周帆week1
  Week1-Database-Introduction/周帆week1/周帆Week1.md
Labels: need review, status/RP1, weekly work

#24 Modify readme
  README.md
Labels: need review, status/RP1

#15 龚凯week1
  Week1-Database-Introduction/gongkaiweek1/images/docker_success.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_0.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_1.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_2.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_3.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_4.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_5.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_6.png
  Week1-Database-Introduction/gongkaiweek1/images/janus_7.png
  Week1-Database-Introduction/gongkaiweek1/images/mongo_1.png
  Week1-Database-Introduction/gongkaiweek1/images/mongo_2.png
  Week1-Database-Introduction/gongkaiweek1/images/mongodb_3.png
  Week1-Database-Introduction/gongkaiweek1/images/mongodb_4.png
  Week1-Database-Introduction/gongkaiweek1/images/mongodb_5.png
  Week1-Database-Introduction/gongkaiweek1/images/mongodb_6.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql3.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql_1.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql_2.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql_4.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql_5.png
  Week1-Database-Introduction/gongkaiweek1/images/mysql_6.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_1.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_2.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_4.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_5.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_6.png
  Week1-Database-Introduction/gongkaiweek1/images/redis_7.png
  Week1-Database-Introduction/gongkaiweek1/images/timg.jpg
  Week1-Database-Introduction/gongkaiweek1/龚凯试验报告.md
Labels: need review, status/RP1, status/RP2, weekly work
